#!/bin/bash

echo "========================================="
echo "📱 FunnyPixels APNs 设备令牌获取指南"
echo "========================================="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1️⃣  在 Xcode 中打开项目："
echo "   cd /Users/ginochow/code/funnypixels3/FunnyPixelsApp"
echo "   open FunnyPixelsApp.xcodeproj"
echo ""
echo "2️⃣  确认构建配置："
echo "   Product → Scheme → Edit Scheme → Run → Build Configuration: Debug"
echo ""
echo "3️⃣  清理并重新构建："
echo "   Product → Clean Build Folder (Cmd+Shift+K)"
echo "   Product → Run (Cmd+R)"
echo ""
echo "4️⃣  在 Xcode 控制台（底部输出窗口）查找设备令牌："
echo "   搜索关键词：\"Device token:\""
echo "   示例日志："
echo "   [INFO] Device token: a1b2c3d4e5f6789..."
echo ""
echo "5️⃣  复制完整的 64 位设备令牌，然后运行："
echo "   cd /Users/ginochow/code/funnypixels3/backend"
echo "   node test-push.js <your_device_token>"
echo ""
echo "========================================="
echo ""
echo "💡 提示："
echo "- 必须使用真机（iPhone/iPad），模拟器不支持推送"
echo "- 确保设备已连接到互联网"
echo "- 首次运行时会请求推送权限，请点击"允许""
echo ""
echo "如果仍然失败，请检查："
echo "- Info.plist 中的 Bundle ID: com.funnypixels.app"
echo "- Entitlements 中的 aps-environment: development"
echo "- 后端 .env 中的 APN_BUNDLE_ID: com.funnypixels.app"
echo ""
