// Generated by scripts/localization/generate_l10n_swift.js
// DO NOT EDIT MANUALLY
import Foundation

enum L10n {
    static func tr(_ key: String, _ args: CVarArg...) -> String {
        LocalizationManager.shared.localizedString(key, args)
    }

    static func plural(_ key: String, count: Int) -> String {
        LocalizationManager.shared.localizedPlural(key, count: count)
    }

    static let supportedLanguages: [(code: String, name: String, nativeName: String)] = [
        ("en", "English", "English"),
        ("zh-Hans", "Chinese (Simplified)", "简体中文"),
        ("ja", "Japanese", "日本語"),
        ("ko", "Korean", "한국어"),
        ("es", "Spanish", "Español"),
        ("pt-BR", "Portuguese (Brazil)", "Português (Brasil)")
    ]

    static var activeFor3Days: String { tr("Active for 3 days") }
    static var activeFor7Days: String { tr("Active for 7 days") }
    static var connectWith5Friends: String { tr("Connect with 5 friends") }
    static var draw1Pixel: String { tr("Draw 1 pixel") }
    static var draw10Pixels: String { tr("Draw 10 pixels") }
    static var draw100Pixels: String { tr("Draw 100 pixels") }
    static var draw1000Pixels: String { tr("Draw 1000 pixels") }
    static var draw10000Pixels: String { tr("Draw 10000 pixels") }
    static var follow10Users: String { tr("Follow 10 users") }
    static var follow20Users: String { tr("Follow 20 users") }
    static var follow5Users: String { tr("Follow 5 users") }
    static var have5Friends: String { tr("Have 5 friends") }
    static var invite5Friends: String { tr("Invite 5 friends") }
    static var pixelArtist: String { tr("Pixel Artist") }
    static var pixelMaster: String { tr("Pixel Master") }
    static var pixelNovice: String { tr("Pixel Novice") }
    static var post5Comments: String { tr("Post 5 comments") }
    static var receive10Likes: String { tr("Receive 10 likes") }
    static var receive100Likes: String { tr("Receive 100 likes") }
    static var receive50Likes: String { tr("Receive 50 likes") }
    static var receive500Likes: String { tr("Receive 500 likes") }
    static var share10Times: String { tr("Share 10 times") }
    static var socialButterfly: String { tr("Social Butterfly") }
    static var achievementBtnClaim: String { tr("achievement.btn.claim") }
    static func achievementClaimSuccess(_ count: Int) -> String { plural("achievement.claim.success", count: count) }
    static var achievementClaimable: String { tr("achievement.claimable") }
    static var achievementCompleted: String { tr("achievement.completed") }
    static var achievementEmptyMessage: String { tr("achievement.empty.message") }
    static var achievementEmptyTitle: String { tr("achievement.empty.title") }
    static var achievementShareUnlock: String { tr("achievement.share.unlock") }
    static var achievementStatsLikes: String { tr("achievement.stats.likes") }
    static var achievementStatsPixels: String { tr("achievement.stats.pixels") }
    static var achievementStatsTitle: String { tr("achievement.stats.title") }
    static var achievementStatsTotal: String { tr("achievement.stats.total") }
    static var achievementStatsUnlocked: String { tr("achievement.stats.unlocked") }
    static var achievementUnlockTitle: String { tr("achievement.unlock.title") }
    static var activeFor3Days_2: String { tr("active for 3 days") }
    static var activeFor7Days_2: String { tr("active for 7 days") }
    static var allianceActionDemote: String { tr("alliance.action.demote") }
    static var allianceActionDissolve: String { tr("alliance.action.dissolve") }
    static var allianceActionKick: String { tr("alliance.action.kick") }
    static var allianceActionLeave: String { tr("alliance.action.leave") }
    static var allianceActionPromote: String { tr("alliance.action.promote") }
    static var allianceActionTransfer: String { tr("alliance.action.transfer") }
    static var allianceApplicationsApproveTitle: String { tr("alliance.applications.approve_title") }
    static var allianceApplicationsEmpty: String { tr("alliance.applications.empty") }
    static var allianceApplicationsRejectTitle: String { tr("alliance.applications.reject_title") }
    static var allianceApplicationsReviewPlaceholder: String { tr("alliance.applications.review_placeholder") }
    static var allianceApplicationsTitle: String { tr("alliance.applications.title") }
    static var allianceBtnApply: String { tr("alliance.btn.apply") }
    static var allianceBtnCreateAction: String { tr("alliance.btn.create_action") }
    static var allianceBtnJoin: String { tr("alliance.btn.join") }
    static var allianceCreate: String { tr("alliance.create") }
    static var allianceCreateName: String { tr("alliance.create.name") }
    static var allianceCreateSuccess: String { tr("alliance.create.success") }
    static var allianceDissolveMessage: String { tr("alliance.dissolve.message") }
    static var allianceDissolveTitle: String { tr("alliance.dissolve.title") }
    static var allianceEditInfo: String { tr("alliance.edit.info") }
    static var allianceEditTitle: String { tr("alliance.edit.title") }
    static var allianceEmptyMessage: String { tr("alliance.empty.message") }
    static var allianceEmptyTitle: String { tr("alliance.empty.title") }
    static var allianceErrorTransferRequired: String { tr("alliance.error.transfer_required") }
    static var allianceFlagColor: String { tr("alliance.flag.color") }
    static var allianceFlagComplex: String { tr("alliance.flag.complex") }
    static var allianceFlagEmoji: String { tr("alliance.flag.emoji") }
    static var allianceFlagEmpty: String { tr("alliance.flag.empty") }
    static var allianceFlagSelect: String { tr("alliance.flag.select") }
    static var allianceFlagType: String { tr("alliance.flag.type") }
    static var allianceFormApproval: String { tr("alliance.form.approval") }
    static var allianceFormBasic: String { tr("alliance.form.basic") }
    static var allianceFormDesc: String { tr("alliance.form.desc") }
    static var allianceFormFlag: String { tr("alliance.form.flag") }
    static var allianceFormName: String { tr("alliance.form.name") }
    static var allianceFormNotice: String { tr("alliance.form.notice") }
    static var allianceFormPattern: String { tr("alliance.form.pattern") }
    static var allianceFormPrivate: String { tr("alliance.form.private") }
    static var allianceFormPublic: String { tr("alliance.form.public") }
    static var allianceFormSettings: String { tr("alliance.form.settings") }
    static var allianceFormVisibility: String { tr("alliance.form.visibility") }
    static var allianceGuestMessage: String { tr("alliance.guest.message") }
    static var allianceGuestTitle: String { tr("alliance.guest.title") }
    static var allianceInviteCopy: String { tr("alliance.invite.copy") }
    static var allianceInviteMessage: String { tr("alliance.invite.message") }
    static var allianceInviteTitle: String { tr("alliance.invite.title") }
    static var allianceLeaveMessage: String { tr("alliance.leave.message") }
    static var allianceLeaveSuccess: String { tr("alliance.leave.success") }
    static var allianceLeaveTitle: String { tr("alliance.leave.title") }
    static var allianceLimitMax: String { tr("alliance.limit.max") }
    static func allianceLimitNeeded(_ count: Int) -> String { plural("alliance.limit.needed", count: count) }
    static var allianceLimitTitle: String { tr("alliance.limit.title") }
    static var allianceLimitUsage: String { tr("alliance.limit.usage") }
    static var allianceMemberJoinDate: String { tr("alliance.member.join_date") }
    static var allianceMembers: String { tr("alliance.members") }
    static var allianceMembersTitle: String { tr("alliance.members.title") }
    static var allianceMenuApplications: String { tr("alliance.menu.applications") }
    static var allianceMenuApplicationsSubtitle: String { tr("alliance.menu.applications.subtitle") }
    static var allianceMenuInvite: String { tr("alliance.menu.invite") }
    static var allianceMenuInviteSubtitle: String { tr("alliance.menu.invite.subtitle") }
    static var allianceMenuMembers: String { tr("alliance.menu.members") }
    static var allianceMenuMembersSubtitle: String { tr("alliance.menu.members.subtitle") }
    static var allianceMenuStats: String { tr("alliance.menu.stats") }
    static var allianceMenuStatsSubtitle: String { tr("alliance.menu.stats.subtitle") }
    static var allianceMsgDissolve: String { tr("alliance.msg.dissolve") }
    static var allianceNoticeEmpty: String { tr("alliance.notice.empty") }
    static var allianceRank: String { tr("alliance.rank") }
    static var allianceRoleAdmin: String { tr("alliance.role.admin") }
    static var allianceRoleLeader: String { tr("alliance.role.leader") }
    static var allianceRoleMember: String { tr("alliance.role.member") }
    static var allianceSearchNoResults: String { tr("alliance.search.no_results") }
    static var allianceSearchPlaceholder: String { tr("alliance.search.placeholder") }
    static var allianceSearchPopular: String { tr("alliance.search.popular") }
    static var allianceSearchSearching: String { tr("alliance.search.searching") }
    static var allianceSelectTitle: String { tr("alliance.select.title") }
    static var allianceStatsCached: String { tr("alliance.stats.cached") }
    static var allianceStatsComparison: String { tr("alliance.stats.comparison") }
    static var allianceStatsComparisonNote: String { tr("alliance.stats.comparison_note") }
    static var allianceStatsCore: String { tr("alliance.stats.core") }
    static var allianceStatsCurrentOwnership: String { tr("alliance.stats.current_ownership") }
    static var allianceStatsInfluence: String { tr("alliance.stats.influence") }
    static var allianceStatsMembers: String { tr("alliance.stats.members") }
    static var allianceStatsNoComparison: String { tr("alliance.stats.no_comparison") }
    static var allianceStatsOwnership: String { tr("alliance.stats.ownership") }
    static var allianceStatsPropContribution: String { tr("alliance.stats.prop_contribution") }
    static var allianceStatsRank: String { tr("alliance.stats.rank") }
    static var allianceStatsReal: String { tr("alliance.stats.real") }
    static var allianceStatsRealtime: String { tr("alliance.stats.realtime") }
    static var allianceStatsTerritory: String { tr("alliance.stats.territory") }
    static var allianceStatsTitle: String { tr("alliance.stats.title") }
    static var allianceStatsTotalDrawPixels: String { tr("alliance.stats.total_draw_pixels") }
    static var allianceStatsTotalPixels: String { tr("alliance.stats.total_pixels") }
    static var allianceStatsWorldRank: String { tr("alliance.stats.world_rank") }
    static var allianceTabMy: String { tr("alliance.tab.my") }
    static var allianceTabSearch: String { tr("alliance.tab.search") }
    static var allianceTitle: String { tr("alliance.title") }
    static var allianceTotalPixels: String { tr("alliance.total_pixels") }
    static var allianceTransferMessage: String { tr("alliance.transfer.message") }
    static var allianceTransferTitle: String { tr("alliance.transfer.title") }
    static var allianceUpdateSuccess: String { tr("alliance.update.success") }
    static var approvalAdDesc: String { tr("approval.ad_desc") }
    static var approvalAdHint: String { tr("approval.ad_hint") }
    static var approvalAdTitle: String { tr("approval.ad_title") }
    static var approvalBalanceLabel: String { tr("approval.balance_label") }
    static var approvalDeployLocation: String { tr("approval.deploy_location") }
    static var approvalDeployTime: String { tr("approval.deploy_time") }
    static var approvalDesc: String { tr("approval.desc") }
    static var approvalImageHint: String { tr("approval.image_hint") }
    static var approvalImageUploadFailed: String { tr("approval.image_upload_failed") }
    static var approvalLocationLoading: String { tr("approval.location.loading") }
    static var approvalLocationNearby: String { tr("approval.location.nearby") }
    static var approvalLocationUnknown: String { tr("approval.location.unknown") }
    static var approvalLocationHint: String { tr("approval.location_hint") }
    static var approvalNavTitleAd: String { tr("approval.nav_title.ad") }
    static var approvalNavTitleFlag: String { tr("approval.nav_title.flag") }
    static var approvalPatternHint: String { tr("approval.pattern_hint") }
    static var approvalPatternName: String { tr("approval.pattern_name") }
    static var approvalPreviewCropTip: String { tr("approval.preview.crop_tip") }
    static var approvalPreviewEmpty: String { tr("approval.preview.empty") }
    static var approvalPreviewGenerating: String { tr("approval.preview.generating") }
    static func approvalPreviewSize(_ count: Int) -> String { plural("approval.preview.size", count: count) }
    static var approvalPreviewTip: String { tr("approval.preview.tip") }
    static var approvalPriceLabel: String { tr("approval.price_label") }
    static var approvalSectionAdPreview: String { tr("approval.section.ad_preview") }
    static var approvalSectionBasicInfo: String { tr("approval.section.basic_info") }
    static var approvalSectionDeploy: String { tr("approval.section.deploy") }
    static var approvalSectionImage: String { tr("approval.section.image") }
    static var approvalSectionPriceInfo: String { tr("approval.section.price_info") }
    static var approvalSelectImage: String { tr("approval.select_image") }
    static var approvalSelectLocation: String { tr("approval.select_location") }
    static var approvalSubmit: String { tr("approval.submit") }
    static var approvalTapToSelect: String { tr("approval.tap_to_select") }
    static var approvalUnknownError: String { tr("approval.unknown_error") }
    static var approvalUploadFailed: String { tr("approval.upload_failed") }
    static var approvalUploading: String { tr("approval.uploading") }
    static var artworkTagFast: String { tr("artwork.tag.fast") }
    static var artworkTagFirstToday: String { tr("artwork.tag.first_today") }
    static var artworkTagHighDensity: String { tr("artwork.tag.high_density") }
    static var artworkTagLongDistance: String { tr("artwork.tag.long_distance") }
    static var artworkTagNewArea: String { tr("artwork.tag.new_area") }
    static var authAnd: String { tr("auth.and") }
    static var authAppleSignIn: String { tr("auth.apple.sign_in") }
    static var authButtonLogin: String { tr("auth.button.login") }
    static var authButtonResend: String { tr("auth.button.resend") }
    static func authButtonResendCountdown(_ count: Int) -> String { plural("auth.button.resend_countdown", count: count) }
    static var authButtonSendCode: String { tr("auth.button.send_code") }
    static var authButtonSignup: String { tr("auth.button.signup") }
    static var authEmailLabel: String { tr("auth.email.label") }
    static var authEmailPlaceholder: String { tr("auth.email.placeholder") }
    static var authErrorInvalidPhone: String { tr("auth.error.invalid_phone") }
    static var authErrorLoginFailed: String { tr("auth.error.login_failed") }
    static var authErrorMissing: String { tr("auth.error.missing") }
    static var authErrorRegisterFailed: String { tr("auth.error.register_failed") }
    static var authErrorSendCodeFailed: String { tr("auth.error.send_code_failed") }
    static var authErrorUsernameLength: String { tr("auth.error.username_length") }
    static var authGoogleSignIn: String { tr("auth.google.sign_in") }
    static var authJoinTab: String { tr("auth.join.tab") }
    static var authLoginTab: String { tr("auth.login.tab") }
    static var authOrContinueWith: String { tr("auth.or_continue_with") }
    static var authPasswordLabel: String { tr("auth.password.label") }
    static var authPasswordPlaceholder: String { tr("auth.password.placeholder") }
    static var authPrivacyLink: String { tr("auth.privacy.link") }
    static var authSlogan: String { tr("auth.slogan") }
    static var authTermsLink: String { tr("auth.terms.link") }
    static var authTermsPrefix: String { tr("auth.terms.prefix") }
    static var authTitle: String { tr("auth.title") }
    static var authToggleToLogin: String { tr("auth.toggle.to_login") }
    static var authToggleToSignup: String { tr("auth.toggle.to_signup") }
    static var authUsernameLabel: String { tr("auth.username.label") }
    static var authUsernamePlaceholder: String { tr("auth.username.placeholder") }
    static var bombConfirmMessage: String { tr("bomb.confirm_message") }
    static var bombConfirmTitle: String { tr("bomb.confirm_title") }
    static var bombConfirmUse: String { tr("bomb.confirm_use") }
    static var bombPlaceHere: String { tr("bomb.place_here") }
    static var bombSelectLocation: String { tr("bomb.select_location") }
    static var categoryActivity: String { tr("category.activity") }
    static var categoryAlliance: String { tr("category.alliance") }
    static var categoryLikes: String { tr("category.likes") }
    static var categoryPixel: String { tr("category.pixel") }
    static var categoryPixels: String { tr("category.pixels") }
    static var categoryShop: String { tr("category.shop") }
    static var categorySocial: String { tr("category.social") }
    static var categorySpecial: String { tr("category.special") }
    static var celebrationFirstPixelSubtitle: String { tr("celebration.first_pixel.subtitle") }
    static var celebrationFirstPixelTitle: String { tr("celebration.first_pixel.title") }
    static var checkInWithAPhoto5Times: String { tr("check-in  with a photo 5 times") }
    static var checkInWithAPhoto5Times_2: String { tr("check-in with a photo 5 times") }
    static var checkinRecoveryBtn: String { tr("checkin.recovery.btn") }
    static func checkinRecoveryDesc(_ count: Int) -> String { plural("checkin.recovery.desc", count: count) }
    static var checkinRecoveryTitle: String { tr("checkin.recovery.title") }
    static func checkinRewardsDay(_ count: Int) -> String { plural("checkin.rewards.day", count: count) }
    static var checkinRewardsTitle: String { tr("checkin.rewards.title") }
    static var commonCancel: String { tr("common.cancel") }
    static var commonClose: String { tr("common.close") }
    static var commonConfirm: String { tr("common.confirm") }
    static var commonDone: String { tr("common.done") }
    static var commonError: String { tr("common.error") }
    static var commonHint: String { tr("common.hint") }
    static var commonLoading: String { tr("common.loading") }
    static var commonLoginRequired: String { tr("common.login_required") }
    static var commonPixels: String { tr("common.pixels") }
    static var commonPoints: String { tr("common.points") }
    static var commonSave: String { tr("common.save") }
    static var commonShare: String { tr("common.share") }
    static var commonSuccess: String { tr("common.success") }
    static var connectWith5Friends_2: String { tr("connect with 5 friends") }
    static var detailBehaviorInfo: String { tr("detail.behavior_info") }
    static var detailCoveredGrids: String { tr("detail.covered_grids") }
    static var detailCreationInfo: String { tr("detail.creation_info") }
    static var detailModeArtwork: String { tr("detail.mode.artwork") }
    static var detailModeData: String { tr("detail.mode.data") }
    static var detailPathShape: String { tr("detail.path_shape") }
    static var disclaimerAdImage: String { tr("disclaimer.ad_image") }
    static var disclaimerAvatar: String { tr("disclaimer.avatar") }
    static var disclaimerFlag: String { tr("disclaimer.flag") }
    static var disclaimerInfoHint: String { tr("disclaimer.info_hint") }
    static var disclaimerTitle: String { tr("disclaimer.title") }
    static var draw1Pixel_2: String { tr("draw 1 pixel") }
    static var draw10Pixels_2: String { tr("draw 10 pixels") }
    static var draw100Pixels_2: String { tr("draw 100 pixels") }
    static var draw1000Pixels_2: String { tr("draw 1000 pixels") }
    static var draw10000Pixels_2: String { tr("draw 10000 pixels") }
    static var drawingColorCurrent: String { tr("drawing.color.current") }
    static var drawingColorPresets: String { tr("drawing.color.presets") }
    static var drawingColorSelectTitle: String { tr("drawing.color.select_title") }
    static var drawingEmojiCurrent: String { tr("drawing.emoji.current") }
    static var drawingEmojiSelectTitle: String { tr("drawing.emoji.select_title") }
    static var drawingEmojiTapToSelect: String { tr("drawing.emoji.tap_to_select") }
    static var drawingGpsActive: String { tr("drawing.gps.active") }
    static var drawingGpsIdle: String { tr("drawing.gps.idle") }
    static var drawingGpsNotActive: String { tr("drawing.gps.not_active") }
    static func drawingGpsSessionPixels(_ count: Int) -> String { plural("drawing.gps.session_pixels", count: count) }
    static var drawingGpsSessionTitle: String { tr("drawing.gps.session_title") }
    static var drawingGpsStart: String { tr("drawing.gps.start") }
    static var drawingGpsStop: String { tr("drawing.gps.stop") }
    static var drawingGpsTitle: String { tr("drawing.gps.title") }
    static var drawingModeColor: String { tr("drawing.mode.color") }
    static var drawingModeComplex: String { tr("drawing.mode.complex") }
    static var drawingModeEmoji: String { tr("drawing.mode.emoji") }
    static var drawingModeGps: String { tr("drawing.mode.gps") }
    static var drawingModeNone: String { tr("drawing.mode.none") }
    static var drawingModeTitle: String { tr("drawing.mode.title") }
    static var drawingDetailReplayButton: String { tr("drawing_detail.replay_button") }
    static var drawingDetailShareButton: String { tr("drawing_detail.share_button") }
    static var drawingDetailTitle: String { tr("drawing_detail.title") }
    static var driftBottleCreateLater: String { tr("drift_bottle.create.later") }
    static var driftBottleCreatePlaceholder: String { tr("drift_bottle.create.placeholder") }
    static func driftBottleCreatePrompt(_ count: Int) -> String { plural("drift_bottle.create.prompt", count: count) }
    static var driftBottleCreateSuccess: String { tr("drift_bottle.create.success") }
    static var driftBottleCreateThrow: String { tr("drift_bottle.create.throw") }
    static var driftBottleCreateTitle: String { tr("drift_bottle.create.title") }
    static var driftBottleCreateYes: String { tr("drift_bottle.create.yes") }
    static func driftBottleDaysCount(_ count: Int) -> String { plural("drift_bottle.days_count", count: count) }
    static var driftBottleEncounterFrom: String { tr("drift_bottle.encounter.from") }
    static var driftBottleEncounterOpen: String { tr("drift_bottle.encounter.open") }
    static func driftBottleEncounterStats(_ count: Int) -> String { plural("drift_bottle.encounter.stats", count: count) }
    static var driftBottleFarAway: String { tr("drift_bottle.far_away") }
    static func driftBottleIndicatorCount(_ count: Int) -> String { plural("drift_bottle.indicator.count", count: count) }
    static var driftBottleIndicatorEarned: String { tr("drift_bottle.indicator.earned") }
    static var driftBottleIndicatorFrozen: String { tr("drift_bottle.indicator.frozen") }
    static func driftBottleIndicatorProgress(_ count: Int) -> String { plural("drift_bottle.indicator.progress", count: count) }
    static func driftBottleJourneyDays(_ count: Int) -> String { plural("drift_bottle.journey.days", count: count) }
    static var driftBottleJourneyLoadFailed: String { tr("drift_bottle.journey.load_failed") }
    static var driftBottleJourneyMessages: String { tr("drift_bottle.journey.messages") }
    static var driftBottleJourneyOrigin: String { tr("drift_bottle.journey.origin") }
    static var driftBottleJourneyRoute: String { tr("drift_bottle.journey.route") }
    static func driftBottleJourneyStations(_ count: Int) -> String { plural("drift_bottle.journey.stations", count: count) }
    static var driftBottleJourneySunk: String { tr("drift_bottle.journey.sunk") }
    static var driftBottleJourneyTitle: String { tr("drift_bottle.journey.title") }
    static var driftBottleJourneyListEmptyMessage: String { tr("drift_bottle.journey_list.empty.message") }
    static var driftBottleJourneyListEmptyTitle: String { tr("drift_bottle.journey_list.empty.title") }
    static var driftBottleJourneyListTitle: String { tr("drift_bottle.journey_list.title") }
    static func driftBottleOpenDays(_ count: Int) -> String { plural("drift_bottle.open.days", count: count) }
    static var driftBottleOpenFrom: String { tr("drift_bottle.open.from") }
    static var driftBottleOpenLastStop: String { tr("drift_bottle.open.last_stop") }
    static var driftBottleOpenLeaveFootprint: String { tr("drift_bottle.open.leave_footprint") }
    static var driftBottleOpenMessagesTitle: String { tr("drift_bottle.open.messages_title") }
    static func driftBottleOpenMiniStats(_ count: Int) -> String { plural("drift_bottle.open.mini_stats", count: count) }
    static var driftBottleOpenOk: String { tr("drift_bottle.open.ok") }
    static var driftBottleOpenOpening: String { tr("drift_bottle.open.opening") }
    static var driftBottleOpenPlaceholder: String { tr("drift_bottle.open.placeholder") }
    static var driftBottleOpenRelease: String { tr("drift_bottle.open.release") }
    static var driftBottleOpenReleased: String { tr("drift_bottle.open.released") }
    static func driftBottleOpenStation(_ count: Int) -> String { plural("drift_bottle.open.station", count: count) }
    static var driftBottleOpenSubmitRelease: String { tr("drift_bottle.open.submit_release") }
    static var driftBottleOpenSunkMessage: String { tr("drift_bottle.open.sunk_message") }
    static var driftBottleOpenSunkTitle: String { tr("drift_bottle.open.sunk_title") }
    static var driftBottleOpenWriteMessage: String { tr("drift_bottle.open.write_message") }
    static var driftBottleReunionDays: String { tr("drift_bottle.reunion.days") }
    static var driftBottleReunionKm: String { tr("drift_bottle.reunion.km") }
    static var driftBottleReunionLetDrift: String { tr("drift_bottle.reunion.let_drift") }
    static var driftBottleReunionOpened: String { tr("drift_bottle.reunion.opened") }
    static var driftBottleReunionOthersMessages: String { tr("drift_bottle.reunion.others_messages") }
    static var driftBottleReunionReadStory: String { tr("drift_bottle.reunion.read_story") }
    static var driftBottleReunionSubtitle: String { tr("drift_bottle.reunion.subtitle") }
    static var driftBottleReunionTitle: String { tr("drift_bottle.reunion.title") }
    static var driftBottleRoleCreator: String { tr("drift_bottle.role.creator") }
    static var driftBottleSomewhere: String { tr("drift_bottle.somewhere") }
    static func driftBottleStationNumber(_ count: Int) -> String { plural("drift_bottle.station_number", count: count) }
    static var driftBottleUnknown: String { tr("drift_bottle.unknown") }
    static var errorAchievementHighlightsFailed: String { tr("error.achievement_highlights_failed") }
    static var errorAchievementListFailed: String { tr("error.achievement_list_failed") }
    static var errorAchievementStatsFailed: String { tr("error.achievement_stats_failed") }
    static var errorCheckAchievementFailed: String { tr("error.check_achievement_failed") }
    static var errorCompletedAchievementFailed: String { tr("error.completed_achievement_failed") }
    static var errorLeaderboardFailed: String { tr("error.leaderboard_failed") }
    static var errorLoadFailed: String { tr("error.load_failed") }
    static var errorRankFailed: String { tr("error.rank_failed") }
    static var errorUpdateFailed: String { tr("error.update_failed") }
    static var errorUserAchievementFailed: String { tr("error.user_achievement_failed") }
    static var eventCenterTabActive: String { tr("event.center.tab.active") }
    static var eventCenterTabEnded: String { tr("event.center.tab.ended") }
    static var eventCenterTabMy: String { tr("event.center.tab.my") }
    static var eventCenterTitle: String { tr("event.center.title") }
    static var eventEmptyActive: String { tr("event.empty.active") }
    static var eventEmptyEnded: String { tr("event.empty.ended") }
    static var eventEmptyMy: String { tr("event.empty.my") }
    static var eventFinalRankings: String { tr("event.final_rankings") }
    static var eventJoinedAt: String { tr("event.joined_at") }
    static var eventNoRankings: String { tr("event.no_rankings") }
    static var eventParticipants: String { tr("event.participants") }
    static var eventPixelLogs: String { tr("event.pixel_logs") }
    static var eventPreannounceStarted: String { tr("event.preannounce.started") }
    static var eventPreannounceStartingSoon: String { tr("event.preannounce.starting_soon") }
    static var eventPreannounceStartsIn: String { tr("event.preannounce.starts_in") }
    static var eventPreannounceTitle: String { tr("event.preannounce.title") }
    static var eventPreannounceViewDetail: String { tr("event.preannounce.view_detail") }
    static var eventResultShare: String { tr("event.result.share") }
    static var eventResultTitle: String { tr("event.result.title") }
    static var eventRewardsSubtitle: String { tr("event.rewards.subtitle") }
    static var eventRewardsTitle: String { tr("event.rewards.title") }
    static var eventRewardsConfig: String { tr("event.rewards_config") }
    static var eventSettled: String { tr("event.settled") }
    static var eventSignupAllianceDesc: String { tr("event.signup.alliance.desc") }
    static var eventSignupIndividual: String { tr("event.signup.individual") }
    static var eventSignupIndividualDesc: String { tr("event.signup.individual.desc") }
    static var eventSignupOrWithAlliance: String { tr("event.signup.or_with_alliance") }
    static var eventSignupTitle: String { tr("event.signup.title") }
    static var eventSignupBtn: String { tr("event.signup_btn") }
    static var eventSignupClosed: String { tr("event.signup_closed") }
    static var eventSignupPrompt: String { tr("event.signup_prompt") }
    static var eventStatsActive: String { tr("event.stats.active") }
    static var eventStatsCompleted: String { tr("event.stats.completed") }
    static var eventStatsParticipated: String { tr("event.stats.participated") }
    static var eventStatusActive: String { tr("event.status.active") }
    static var eventStatusDraft: String { tr("event.status.draft") }
    static var eventStatusEnded: String { tr("event.status.ended") }
    static var eventStatusPublished: String { tr("event.status.published") }
    static var eventTargetAllianceLeader: String { tr("event.target.alliance_leader") }
    static var eventTargetAllianceMembers: String { tr("event.target.alliance_members") }
    static var eventTargetUser: String { tr("event.target.user") }
    static var eventTotalPixels: String { tr("event.total_pixels") }
    static var eventTypeCooperation: String { tr("event.type.cooperation") }
    static var eventTypeLeaderboard: String { tr("event.type.leaderboard") }
    static var eventTypeTerritory: String { tr("event.type.territory") }
    static var eventTypeWar: String { tr("event.type.war") }
    static var eventZoneEndedSubtitle: String { tr("event.zone.ended.subtitle") }
    static var eventZoneEndedTitle: String { tr("event.zone.ended.title") }
    static func eventZoneEndingSubtitle(_ count: Int) -> String { plural("event.zone.ending.subtitle", count: count) }
    static var eventZoneEndingTitle: String { tr("event.zone.ending.title") }
    static var eventZoneEnteredSubtitle: String { tr("event.zone.entered.subtitle") }
    static var eventZoneEnteredTitle: String { tr("event.zone.entered.title") }
    static var eventZoneExitedSubtitle: String { tr("event.zone.exited.subtitle") }
    static var eventZoneExitedTitle: String { tr("event.zone.exited.title") }
    static var exploreEmpty: String { tr("explore.empty") }
    static var exploreEmptyHint: String { tr("explore.empty.hint") }
    static var exploreTitle: String { tr("explore.title") }
    static var follow10Users_2: String { tr("follow 10 users") }
    static var follow20Users_2: String { tr("follow 20 users") }
    static var follow5Users_2: String { tr("follow 5 users") }
    static var galleryEmptyMessage: String { tr("gallery.empty.message") }
    static var galleryEmptyTitle: String { tr("gallery.empty.title") }
    static var galleryGuestMessage: String { tr("gallery.guest.message") }
    static var galleryGuestTitle: String { tr("gallery.guest.title") }
    static var galleryTitle: String { tr("gallery.title") }
    static var gpsSessionLabel: String { tr("gps.session.label") }
    static var gpsSessionTitle: String { tr("gps.session.title") }
    static var gpsSessionUnit: String { tr("gps.session.unit") }
    static var gpsStopButton: String { tr("gps.stop.button") }
    static var gpsTelemetryAmmo: String { tr("gps.telemetry.ammo") }
    static var gpsTelemetryFrozen: String { tr("gps.telemetry.frozen") }
    static var gpsTelemetryLifetime: String { tr("gps.telemetry.lifetime") }
    static var have5Friends_2: String { tr("have 5 friends") }
    static var helpFeedbackContactPlaceholder: String { tr("help.feedback.contact_placeholder") }
    static var helpFeedbackContactTitle: String { tr("help.feedback.contact_title") }
    static var helpFeedbackPlaceholder: String { tr("help.feedback.placeholder") }
    static var helpFeedbackSection: String { tr("help.feedback.section") }
    static var helpFeedbackSubmit: String { tr("help.feedback.submit") }
    static var helpFeedbackSuccessMessage: String { tr("help.feedback.success_message") }
    static var helpFeedbackSuccessTitle: String { tr("help.feedback.success_title") }
    static var helpManualAllianceDesc: String { tr("help.manual.alliance_desc") }
    static var helpManualAllianceTitle: String { tr("help.manual.alliance_title") }
    static var helpManualHowDesc: String { tr("help.manual.how_desc") }
    static var helpManualHowTitle: String { tr("help.manual.how_title") }
    static var helpManualShopDesc: String { tr("help.manual.shop_desc") }
    static var helpManualShopTitle: String { tr("help.manual.shop_title") }
    static var helpManualWelcomeDesc: String { tr("help.manual.welcome_desc") }
    static var helpManualWelcomeTitle: String { tr("help.manual.welcome_title") }
    static var helpSegmentFeedback: String { tr("help.segment.feedback") }
    static var helpSegmentManual: String { tr("help.segment.manual") }
    static var helpSegmentTitle: String { tr("help.segment.title") }
    static var helpTitle: String { tr("help.title") }
    static var historyDistance: String { tr("history.distance") }
    static var historyDuration: String { tr("history.duration") }
    static var historyEmptyMessage: String { tr("history.empty.message") }
    static var historyEmptyTitle: String { tr("history.empty.title") }
    static var historyFilterCity: String { tr("history.filter.city") }
    static var historyFilterCityPlaceholder: String { tr("history.filter.city_placeholder") }
    static var historyFilterDate: String { tr("history.filter.date") }
    static var historyFilterDone: String { tr("history.filter.done") }
    static var historyFilterEnableDate: String { tr("history.filter.enable_date") }
    static var historyFilterEndDate: String { tr("history.filter.end_date") }
    static var historyFilterReset: String { tr("history.filter.reset") }
    static var historyFilterStartDate: String { tr("history.filter.start_date") }
    static var historyFilterStatus: String { tr("history.filter.status") }
    static var historyFilterTitle: String { tr("history.filter.title") }
    static var historyFilterType: String { tr("history.filter.type") }
    static var historyGuestMessage: String { tr("history.guest.message") }
    static var historyGuestTitle: String { tr("history.guest.title") }
    static var historyLoginRegister: String { tr("history.login_register") }
    static var historyStatsPixels: String { tr("history.stats.pixels") }
    static var historyStatusActive: String { tr("history.status.active") }
    static var historyTitle: String { tr("history.title") }
    static var inventoryEmptyMessage: String { tr("inventory.empty.message") }
    static var inventoryEmptyTitle: String { tr("inventory.empty.title") }
    static var inventoryTitle: String { tr("inventory.title") }
    static var inventoryUse: String { tr("inventory.use") }
    static var invite5Friends_2: String { tr("invite 5 friends") }
    static var inviteCopied: String { tr("invite.copied") }
    static var inviteCopy: String { tr("invite.copy") }
    static var inviteErrorAlready: String { tr("invite.error_already") }
    static var inviteErrorGeneric: String { tr("invite.error_generic") }
    static var inviteErrorInvalid: String { tr("invite.error_invalid") }
    static var inviteErrorSelf: String { tr("invite.error_self") }
    static func inviteInviteeReward(_ count: Int) -> String { plural("invite.invitee_reward", count: count) }
    static func inviteInviterReward(_ count: Int) -> String { plural("invite.inviter_reward", count: count) }
    static var inviteNavTitle: String { tr("invite.nav_title") }
    static var inviteRedeemButton: String { tr("invite.redeem_button") }
    static var inviteRedeemPlaceholder: String { tr("invite.redeem_placeholder") }
    static func inviteRedeemSuccess(_ count: Int) -> String { plural("invite.redeem_success", count: count) }
    static var inviteRedeemTitle: String { tr("invite.redeem_title") }
    static var inviteRewardsTitle: String { tr("invite.rewards_title") }
    static var inviteShare: String { tr("invite.share") }
    static var inviteShareMessage: String { tr("invite.share_message") }
    static var inviteStatsEarned: String { tr("invite.stats_earned") }
    static var inviteStatsInvited: String { tr("invite.stats_invited") }
    static var inviteSubtitle: String { tr("invite.subtitle") }
    static var inviteTitle: String { tr("invite.title") }
    static var inviteYourCode: String { tr("invite.your_code") }
    static var leaderboardEmpty: String { tr("leaderboard.empty") }
    static var leaderboardPeriodAlltime: String { tr("leaderboard.period.alltime") }
    static var leaderboardPeriodDay: String { tr("leaderboard.period.day") }
    static var leaderboardPeriodMonth: String { tr("leaderboard.period.month") }
    static var leaderboardPeriodWeek: String { tr("leaderboard.period.week") }
    static var leaderboardPickerPeriod: String { tr("leaderboard.picker.period") }
    static var leaderboardPickerType: String { tr("leaderboard.picker.type") }
    static var leaderboardPixel: String { tr("leaderboard.pixel") }
    static var leaderboardTitle: String { tr("leaderboard.title") }
    static var leaderboardTypeAlliance: String { tr("leaderboard.type.alliance") }
    static var leaderboardTypeCity: String { tr("leaderboard.type.city") }
    static var leaderboardTypePersonal: String { tr("leaderboard.type.personal") }
    static var leaderboardUsers: String { tr("leaderboard.users") }
    static var loading: String { tr("loading") }
    static var locationPreEduEnable: String { tr("location.pre_edu.enable") }
    static var locationPreEduFeature1Desc: String { tr("location.pre_edu.feature1.desc") }
    static var locationPreEduFeature1Title: String { tr("location.pre_edu.feature1.title") }
    static var locationPreEduFeature2Desc: String { tr("location.pre_edu.feature2.desc") }
    static var locationPreEduFeature2Title: String { tr("location.pre_edu.feature2.title") }
    static var locationPreEduFeature3Desc: String { tr("location.pre_edu.feature3.desc") }
    static var locationPreEduFeature3Title: String { tr("location.pre_edu.feature3.title") }
    static var locationPreEduSkip: String { tr("location.pre_edu.skip") }
    static var locationPreEduSubtitle: String { tr("location.pre_edu.subtitle") }
    static var locationPreEduTitle: String { tr("location.pre_edu.title") }
    static func mapModeDrawing(_ count: Int) -> String { plural("map.mode.drawing", count: count) }
    static var onboardingDescAlliance: String { tr("onboarding.desc.alliance") }
    static var onboardingDescExplore: String { tr("onboarding.desc.explore") }
    static var onboardingDescGps: String { tr("onboarding.desc.gps") }
    static var onboardingNext: String { tr("onboarding.next") }
    static var onboardingSkip: String { tr("onboarding.skip") }
    static var onboardingStart: String { tr("onboarding.start") }
    static var onboardingTitleAlliance: String { tr("onboarding.title.alliance") }
    static var onboardingTitleExplore: String { tr("onboarding.title.explore") }
    static var onboardingTitleGps: String { tr("onboarding.title.gps") }
    static var orderStatusCompleted: String { tr("order.status.completed") }
    static var orderStatusFailed: String { tr("order.status.failed") }
    static var orderStatusPending: String { tr("order.status.pending") }
    static var patternAllianceColor: String { tr("pattern.alliance_color") }
    static var patternAllianceFlag: String { tr("pattern.alliance_flag") }
    static var patternAllianceFlagEmoji: String { tr("pattern.alliance_flag_emoji") }
    static var patternDefaultColor: String { tr("pattern.default_color") }
    static var patternLoadingAllianceFlag: String { tr("pattern.loading_alliance_flag") }
    static var patternTypeColor: String { tr("pattern.type.color") }
    static var patternTypeComplex: String { tr("pattern.type.complex") }
    static var patternTypeEmoji: String { tr("pattern.type.emoji") }
    static var pixelArtist_2: String { tr("pixel artist") }
    static var pixelMaster_2: String { tr("pixel master") }
    static var pixelNovice_2: String { tr("pixel novice") }
    static var policyClose: String { tr("policy.close") }
    static var policyLoading: String { tr("policy.loading") }
    static var policyPrivacyTitle: String { tr("policy.privacy.title") }
    static var policyRetry: String { tr("policy.retry") }
    static var policyTermsTitle: String { tr("policy.terms.title") }
    static var post5Comments_2: String { tr("post 5 comments") }
    static var privacyHideAlliance: String { tr("privacy.hide_alliance") }
    static var privacyHideFlag: String { tr("privacy.hide_flag") }
    static var privacyHideNickname: String { tr("privacy.hide_nickname") }
    static var privacyShieldDesc: String { tr("privacy.shield_desc") }
    static var privacyShieldTitle: String { tr("privacy.shield_title") }
    static var privacyTitle: String { tr("privacy.title") }
    static var profileAchievements: String { tr("profile.achievements") }
    static var profileEditCancel: String { tr("profile.edit.cancel") }
    static var profileEditInfo: String { tr("profile.edit.info") }
    static var profileEditMotto: String { tr("profile.edit.motto") }
    static var profileEditNickname: String { tr("profile.edit.nickname") }
    static var profileEditSave: String { tr("profile.edit.save") }
    static var profileEditTitle: String { tr("profile.edit.title") }
    static var profileEventCenter: String { tr("profile.event_center") }
    static var profileFeatures: String { tr("profile.features") }
    static var profileGuestMessage: String { tr("profile.guest.message") }
    static var profileGuestTitle: String { tr("profile.guest.title") }
    static var profileHonors: String { tr("profile.honors") }
    static var profileInviteFriends: String { tr("profile.invite_friends") }
    static var profileItems: String { tr("profile.items") }
    static var profileJourneyCollection: String { tr("profile.journey_collection") }
    static var profileLogout: String { tr("profile.logout") }
    static var profileLogoutConfirmMessage: String { tr("profile.logout.confirm.message") }
    static var profileLogoutConfirmTitle: String { tr("profile.logout.confirm.title") }
    static var profileMessages: String { tr("profile.messages") }
    static var profilePoints: String { tr("profile.points") }
    static var profileSettings: String { tr("profile.settings") }
    static var profileShop: String { tr("profile.shop") }
    static var profileViewAll: String { tr("profile.view_all") }
    static var rank1st: String { tr("rank.1st") }
    static var rank2nd: String { tr("rank.2nd") }
    static var rank3rd: String { tr("rank.3rd") }
    static var rarityCommon: String { tr("rarity.common") }
    static var rarityEpic: String { tr("rarity.epic") }
    static var rarityLegendary: String { tr("rarity.legendary") }
    static var rarityRare: String { tr("rarity.rare") }
    static var rarityUncommon: String { tr("rarity.uncommon") }
    static var receive10Likes_2: String { tr("receive 10 likes") }
    static var receive100Likes_2: String { tr("receive 100 likes") }
    static var receive50Likes_2: String { tr("receive 50 likes") }
    static var receive500Likes_2: String { tr("receive 500 likes") }
    static var rewardFlag: String { tr("reward.flag") }
    static var rewardTargetLeader: String { tr("reward.target.leader") }
    static var rewardTargetMembers: String { tr("reward.target.members") }
    static var sessionValidating: String { tr("session.validating") }
    static var sessionDetailGeneratingMap: String { tr("session_detail.generating_map") }
    static var sessionDetailShareButton: String { tr("session_detail.share.button") }
    static var sessionDetailShareCta: String { tr("session_detail.share.cta") }
    static var sessionDetailShareSubtitle: String { tr("session_detail.share.subtitle") }
    static var sessionDetailShareTitle: String { tr("session_detail.share.title") }
    static var settingsAbout: String { tr("settings.about") }
    static var settingsDisplay: String { tr("settings.display") }
    static var settingsFontLarge: String { tr("settings.font.large") }
    static var settingsFontMedium: String { tr("settings.font.medium") }
    static var settingsFontSmall: String { tr("settings.font.small") }
    static var settingsFontDesc: String { tr("settings.font_desc") }
    static var settingsFontSize: String { tr("settings.font_size") }
    static var settingsHelp: String { tr("settings.help") }
    static var settingsLanguage: String { tr("settings.language") }
    static var settingsLanguageRestartHint: String { tr("settings.language.restart_hint") }
    static var settingsLanguageSystem: String { tr("settings.language.system") }
    static var settingsPixelPrivacy: String { tr("settings.pixel_privacy") }
    static var settingsPreview: String { tr("settings.preview") }
    static var settingsPrivacy: String { tr("settings.privacy") }
    static var settingsSound: String { tr("settings.sound") }
    static var settingsSoundEffects: String { tr("settings.sound_effects") }
    static var settingsVersion: String { tr("settings.version") }
    static var share10Times_2: String { tr("share 10 times") }
    static var shareLinkCopied: String { tr("share.link_copied") }
    static var shareOpened: String { tr("share.opened") }
    static var shareSaveFailed: String { tr("share.save_failed") }
    static var shareSaveSuccess: String { tr("share.save_success") }
    static var shopBackpack: String { tr("shop.backpack") }
    static var shopCategoryAll: String { tr("shop.category.all") }
    static var shopCategoryConsumable: String { tr("shop.category.consumable") }
    static var shopCategoryCosmetic: String { tr("shop.category.cosmetic") }
    static var shopCategorySpecial: String { tr("shop.category.special") }
    static var shopEmptyMessage: String { tr("shop.empty.message") }
    static var shopEmptyTitle: String { tr("shop.empty.title") }
    static var shopErrorInventoryLoadFailed: String { tr("shop.error.inventory_load_failed") }
    static var shopErrorLoadFailed: String { tr("shop.error.load_failed") }
    static var shopErrorPurchaseFailed: String { tr("shop.error.purchase_failed") }
    static var shopErrorRechargeFailed: String { tr("shop.error.recharge_failed") }
    static var shopErrorUseFailed: String { tr("shop.error.use_failed") }
    static var shopInsufficientPointsHint: String { tr("shop.insufficient_points.hint") }
    static func shopInsufficientPointsMessage(_ count: Int) -> String { plural("shop.insufficient_points.message", count: count) }
    static var shopInsufficientPointsRecharge: String { tr("shop.insufficient_points.recharge") }
    static var shopInsufficientPointsTitle: String { tr("shop.insufficient_points.title") }
    static var shopItemUsed: String { tr("shop.item.used") }
    static var shopMyPoints: String { tr("shop.my_points") }
    static func shopPricePoints(_ count: Int) -> String { plural("shop.price_points", count: count) }
    static var shopPurchaseButton: String { tr("shop.purchase.button") }
    static func shopPurchaseConfirmMessage(_ count: Int) -> String { plural("shop.purchase.confirm_message", count: count) }
    static var shopPurchaseConfirmTitle: String { tr("shop.purchase.confirm_title") }
    static var shopTitle: String { tr("shop.title") }
    static var socialButterfly_2: String { tr("social butterfly") }
    static var summaryActivityDescription: String { tr("summary.activity_description") }
    static var summaryArtworkTag: String { tr("summary.artwork_tag") }
    static var summaryButtonClose: String { tr("summary.button.close") }
    static var summaryButtonShare: String { tr("summary.button.share") }
    static var summaryCreatedBy: String { tr("summary.created_by") }
    static var summaryCta: String { tr("summary.cta") }
    static var summaryJoinNow: String { tr("summary.join_now") }
    static var summaryKm: String { tr("summary.km") }
    static var summaryMapGenerating: String { tr("summary.map.generating") }
    static var summaryPixels: String { tr("summary.pixels") }
    static var summaryShareTitle: String { tr("summary.share.title") }
    static var summaryShareText: String { tr("summary.share_text") }
    static var summaryStatsActionArea: String { tr("summary.stats.action_area") }
    static var summaryStatsActionFast: String { tr("summary.stats.action_fast") }
    static var summaryStatsDurationLabel: String { tr("summary.stats.duration_label") }
    static func summaryStatsPixelsLabel(_ count: Int) -> String { plural("summary.stats.pixels_label", count: count) }
    static var summarySubtitle: String { tr("summary.subtitle") }
    static var summaryTime: String { tr("summary.time") }
    static var summaryTitle: String { tr("summary.title") }
    static var summaryWatermark: String { tr("summary.watermark") }
    static var tabAlliance: String { tr("tab.alliance") }
    static var tabHistory: String { tr("tab.history") }
    static var tabLeaderboard: String { tr("tab.leaderboard") }
    static var tabMap: String { tr("tab.map") }
    static var tabProfile: String { tr("tab.profile") }
    static var tooltipFabStartDrawing: String { tr("tooltip.fab.start_drawing") }
    static var transactionDateEnd: String { tr("transaction.date.end") }
    static var transactionDateStart: String { tr("transaction.date.start") }
    static var transactionEmptyMessage: String { tr("transaction.empty.message") }
    static var transactionEmptyTitle: String { tr("transaction.empty.title") }
    static var transactionPointsUsed: String { tr("transaction.points.used") }
    static var transactionStatusCompleted: String { tr("transaction.status.completed") }
    static var transactionStatusFailed: String { tr("transaction.status.failed") }
    static var transactionStatusPending: String { tr("transaction.status.pending") }
    static var transactionTitle: String { tr("transaction.title") }
    static var transactionTypeOther: String { tr("transaction.type.other") }
    static var transactionTypePurchase: String { tr("transaction.type.purchase") }
    static var transactionTypeRefund: String { tr("transaction.type.refund") }
    static var transactionTypeUse: String { tr("transaction.type.use") }
    static var walletAlipay: String { tr("wallet.alipay") }
    static var walletDone: String { tr("wallet.done") }
    static var walletEmptyRechargeMessage: String { tr("wallet.empty_recharge.message") }
    static var walletEmptyRechargeTitle: String { tr("wallet.empty_recharge.title") }
    static var walletEmptySpendingMessage: String { tr("wallet.empty_spending.message") }
    static var walletEmptySpendingTitle: String { tr("wallet.empty_spending.title") }
    static var walletLoadingProducts: String { tr("wallet.loading_products") }
    static var walletMock: String { tr("wallet.mock") }
    static var walletOrderCreated: String { tr("wallet.order_created") }
    static var walletPaymentHint: String { tr("wallet.payment_hint") }
    static func walletPaymentSuccess(_ count: Int) -> String { plural("wallet.payment_success", count: count) }
    static var walletProductLoadFailed: String { tr("wallet.product_load_failed") }
    static var walletRechargeHistory: String { tr("wallet.recharge_history") }
    static func walletRechargePoints(_ count: Int) -> String { plural("wallet.recharge_points", count: count) }
    static var walletSelectAmount: String { tr("wallet.select_amount") }
    static var walletSelectPayment: String { tr("wallet.select_payment") }
    static var walletSpendingHistory: String { tr("wallet.spending_history") }
    static var walletTabBills: String { tr("wallet.tab.bills") }
    static var walletTabRecharge: String { tr("wallet.tab.recharge") }
    static var walletTitle: String { tr("wallet.title") }
    static var walletWechat: String { tr("wallet.wechat") }
}
