#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const stringsPath = path.resolve(__dirname, '../../FunnyPixelsApp/FunnyPixelsApp/Resources/en.lproj/Localizable.strings');
const outputPath = path.resolve(__dirname, '../../FunnyPixelsApp/FunnyPixelsApp/Utilities/Localization/L10n.generated.swift');

if (!fs.existsSync(stringsPath)) {
  console.error(`Localizable.strings not found at ${stringsPath}`);
  process.exit(1);
}

const content = fs.readFileSync(stringsPath, 'utf8');
const lines = content.split(/\r?\n/);
const entries = [];
const entryValues = {};
const keyRegex = /^\s*"([^"]+)"\s*=\s*"(.*)"\s*;\s*$/;

for (const line of lines) {
  const match = line.match(keyRegex);
  if (match) {
    entries.push(match[1]);
    entryValues[match[1]] = match[2];
  }
}

function toIdentifier(key) {
  const parts = key.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  if (parts.length === 0) return 'key';
  const [first, ...rest] = parts;
  const base = first.toLowerCase() + rest.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
  const cleaned = base.replace(/^[^a-zA-Z_]+/, '_');
  return cleaned.length ? cleaned : 'key';
}

const used = new Map();
function uniqueName(name) {
  const count = used.get(name) || 0;
  used.set(name, count + 1);
  if (count === 0) return name;
  return `${name}_${count + 1}`;
}

// Detect plural-eligible keys (contain %d and countable nouns)
function isPluralKey(key, value) {
  return value && value.includes('%d');
}

const sorted = Array.from(new Set(entries)).sort();

const linesOut = [];
linesOut.push('// Generated by scripts/localization/generate_l10n_swift.js');
linesOut.push('// DO NOT EDIT MANUALLY');
linesOut.push('import Foundation');
linesOut.push('');
linesOut.push('enum L10n {');
linesOut.push('    static func tr(_ key: String, _ args: CVarArg...) -> String {');
linesOut.push('        LocalizationManager.shared.localizedString(key, args)');
linesOut.push('    }');
linesOut.push('');
linesOut.push('    static func plural(_ key: String, count: Int) -> String {');
linesOut.push('        LocalizationManager.shared.localizedPlural(key, count: count)');
linesOut.push('    }');
linesOut.push('');
linesOut.push('    static let supportedLanguages: [(code: String, name: String, nativeName: String)] = [');
linesOut.push('        ("en", "English", "English"),');
linesOut.push('        ("zh-Hans", "Chinese (Simplified)", "简体中文"),');
linesOut.push('        ("ja", "Japanese", "日本語"),');
linesOut.push('        ("ko", "Korean", "한국어"),');
linesOut.push('        ("es", "Spanish", "Español"),');
linesOut.push('        ("pt-BR", "Portuguese (Brazil)", "Português (Brasil)")');
linesOut.push('    ]');
linesOut.push('');

for (const key of sorted) {
  const name = uniqueName(toIdentifier(key));
  const value = entryValues[key] || '';

  if (isPluralKey(key, value)) {
    // Generate plural method for keys containing %d
    linesOut.push(`    static func ${name}(_ count: Int) -> String { plural("${key}", count: count) }`);
  } else {
    linesOut.push(`    static var ${name}: String { tr("${key}") }`);
  }
}

linesOut.push('}');
linesOut.push('');

fs.writeFileSync(outputPath, linesOut.join('\n'));
console.log(`Generated ${outputPath} with ${sorted.length} keys`);
