// users 种子数据
const bcrypt = require('bcryptjs');

exports.seed = async function (knex) {
  // 清空现有数据
  await knex('users').del();

  // 生成密码哈希
  const testPasswordHash = '$2a$10$test.hash.for.testing.purposes.only';
  // admin123 hash (cost 10) - generated for consistency
  // We can use a fixed hash or generate one on the fly. 
  // For seed data, generating it ensures it works with current salt settings, but might be slow?
  // Actually, let's just generate it synchronously or await it.
  const adminPasswordHash = await bcrypt.hash('admin123', 10);

  // 插入种子数据
  await knex('users').insert([
    {
      'id': 'b16dceb6-5237-4134-a97b-d8893136db2d',
      'username': 'admin',
      'email': 'admin@funnypixels.com',
      'password_hash': adminPasswordHash,
      'display_name': 'System Admin',
      'avatar_url': null,
      'bio': 'System administrator account',
      'level': 100,
      'experience': 999999,
      'coins': 999999,
      'gems': 999999,
      'is_guest': false,
      'guest_id': null,
      'created_at': new Date(),
      'updated_at': new Date(),
      'last_login': new Date(),
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'super_admin',
      'motto': 'System Administrator',
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 999999
    },
    {
      'id': 'fe89a000-5f45-4118-aa99-46e6985bc519',
      'username': 'testuser',
      'email': 'test@example.com',
      'password_hash': testPasswordHash,
      'display_name': null,
      'avatar_url': null,
      'bio': null,
      'level': 1,
      'experience': 0,
      'coins': 100,
      'gems': 10,
      'is_guest': false,
      'guest_id': null,
      'created_at': '2025-09-06T13:30:20.018Z',
      'updated_at': '2025-09-06T13:30:20.018Z',
      'last_login': null,
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'user',
      'motto': null,
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 0
    },
    {
      'id': '0180c670-e3bb-4cbf-a876-0095105eecc8',
      'username': 'testuser2',
      'email': 'test2@example.com',
      'password_hash': testPasswordHash,
      'display_name': '测试用户2',
      'avatar_url': 'https://api.dicebear.com/7.x/avatars/svg?seed=testuser2',
      'bio': '这是测试用户2',
      'level': 1,
      'experience': 0,
      'coins': 100,
      'gems': 10,
      'is_guest': false,
      'guest_id': null,
      'created_at': '2025-09-06T13:30:20.018Z',
      'updated_at': '2025-09-06T13:30:20.018Z',
      'last_login': null,
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'user',
      'motto': null,
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 0
    },
    {
      'id': '661bdcc1-b4dd-4c76-8c73-7331a80732e0',
      'username': 'testuser1',
      'email': 'test1@example.com',
      'password_hash': testPasswordHash,
      'display_name': '测试用户1',
      'avatar_url': 'https://api.dicebear.com/7.x/avatars/svg?seed=testuser1',
      'bio': '这是测试用户1',
      'level': 1,
      'experience': 0,
      'coins': 100,
      'gems': 10,
      'is_guest': false,
      'guest_id': null,
      'created_at': '2025-09-06T13:30:20.018Z',
      'updated_at': '2025-09-06T13:30:20.018Z',
      'last_login': '2025-09-02T08:46:46.318Z',
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'user',
      'motto': null,
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 0
    },
    {
      'id': 'd2a6c9c0-10d3-4e5f-a307-d8d05e9f4ba2',
      'username': 'abcabc',
      'email': 'abcabc@example.com',
      'password_hash': testPasswordHash,
      'display_name': 'abcabc',
      'avatar_url': null,
      'bio': null,
      'level': 1,
      'experience': 0,
      'coins': 100,
      'gems': 10,
      'is_guest': false,
      'guest_id': null,
      'created_at': '2025-09-06T13:30:20.018Z',
      'updated_at': '2025-09-06T13:30:20.018Z',
      'last_login': null,
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'user',
      'motto': null,
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 0
    },
    {
      'id': 'a79a1fbe-0f97-4303-b922-52b35e6948d5',
      'username': 'bcd',
      'email': 'bcd@example.com',
      'password_hash': testPasswordHash,
      'display_name': 'bcd',
      'avatar_url': null,
      'bio': null,
      'level': 1,
      'experience': 0,
      'coins': 100,
      'gems': 10,
      'is_guest': false,
      'guest_id': null,
      'created_at': '2025-09-06T13:30:20.018Z',
      'updated_at': '2025-09-06T13:30:20.018Z',
      'last_login': null,
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'user',
      'motto': null,
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 0
    },
    {
      'id': '48461d35-26d4-4bc9-83e8-1292002de1da',
      'username': 'avatar_test_user_1757000778445',
      'email': 'avatar_test_1757000778445@example.com',
      'password_hash': testPasswordHash,
      'display_name': '头像测试用户',
      'avatar_url': 'https://api.dicebear.com/7.x/avatars/svg?seed=avatar_test_user',
      'bio': null,
      'level': 1,
      'experience': 0,
      'coins': 100,
      'gems': 10,
      'is_guest': false,
      'guest_id': null,
      'created_at': '2025-09-06T13:30:20.018Z',
      'updated_at': '2025-09-06T13:30:20.018Z',
      'last_login': null,
      'is_online': false,
      'is_banned': false,
      'ban_reason': null,
      'preferences': null,
      'phone': null,
      'role': 'user',
      'motto': null,
      'privacy_mode': false,
      'total_pixels': 0,
      'current_pixels': 0
    }
  ]);

  console.log('✅ users: 插入了 7 条记录 (含 admin)');
};